### ISSUE TITLE
updateEventsのmayMoreFlagは、自発的に送信する場合も必須か？

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/HAPI-2.0-Specification#12]
mayMoreFlagは、M(andatory)となっていますが、自発的に送る場合も必要かとう疑問が生じました。

**Comment by kz0817** [comment]
大量のイベントを分割して送る場合に、サーバー側がそれを知っておくとベターな場面があるから、Mとしているんでしたっけ？

**Comment by masa0612** [comment]
確かにfetchに対するレスポンスとして送る場合のみに必要なもののため，必ずしもMでは無いと思います。
Oにしたほうが良いかもしれません。

**Comment by masa0612** [comment]
Change in 72b95f5ac814ede3ff82030
