### ISSUE TITLE
updatesEventのstatusメンバの必要性

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/HAPI-2.0-Specification#14]
当初のHatoholでは、Zabbixの振る舞いを踏襲してたので、Eventにtriggerのstatusとeventのstatusを両方含ませていた。現在のdraftでは、typeとstatusがそれに相当する。しかし、statusに含まれることは、typeで表現できるので冗長であると感じる。statusを削除することを提案する。

**Comment by kz0817** [comment]
ただ、トリガの情報もイベントに格納しておきたいということもあるので、削除でなく、O(ptionnal)にするほうがよいのかも。

**Comment by masa0612** [comment]
イベントに関してはbrief以外のメンバ全てに上記のことが言えると思います。
（briefさえあれば，イベントとしての最低限の役割は果たせるため）

つまりbrief以外の値は全てOptionalと同義なのですが，現在の仕様書ではtriggerIdのみOptionalです。
仮にbrief以外の値をプラグインが送る際，現在はMandatoryなので空文字にせざるを得ないのですが，
ここをOptionalにしておけば，そもそも送る必要がなくなります。
（その分，サーバー側での処理が増える）

私個人としてはbrief以外全てOptionalにしてしまう方針で良いと思います。

@ashie @cosmo0920 現在サーバー側の実装を行っているお二方はどちらが良いと思いますか？

**Comment by kz0817** [comment]
timeは、Mandatoryでもいいと思います。
プラグインで追加するのも、それほど面倒ではないですし。まあ、なければ、Hatoholサーバで到着時の時刻をつけるということもそれほど難しくありませんが。

**Comment by ashie** [comment]
timeはMandatoryにすべきだと思います。
statusはともかくtypeはMandatoryの方がいいような気がします。

**Comment by cosmo0920** [comment]
time, typeはMandatoryにするべきだと思います。statusはO(ptional)でも良いと思います。

**Comment by ashie** [comment]
2015/06/11リアルミーティングにて:
- triggerId、status、severity、hostId、hostName、extendedInfoはOptionalとする
- eventsオブジェクトの説明でseverityの説明が「トリガー種別」となっているが、「深刻度」に修正

**Comment by ashie** [comment]
> eventsオブジェクトの説明でseverityの説明が「トリガー種別」となっているが、「深刻度」に修正

これは #48 は修正した

**Comment by masa0612** [comment]
> triggerId、status、severity、hostId、hostName、extendedInfoはOptionalとする

#56で修正

**Comment by cosmo0920** [comment]
:+1:

**Comment by masa0612** [comment]
ガリガリIssueを反映していきますぜ
