### ISSUE TITLE
時刻のTimezone

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/HAPI-2.0-Specification#15]
時刻のフォーマットの説明はありますが、どのタイムゾーンの時刻かの記載がありません。
使用地域にかかわらず、UTCを使用するのが、シンプルでよいと思います。

**Comment by cosmo0920** [comment]
賛成です。
UTCとしてDBに保存しておけば後から時刻をユーザーのタイムゾーンに合わせて表示したくなった時に扱いやすいと考えられるからです。

**Comment by ashie** [comment]
#55 で反映した
