### ISSUE TITLE
updateTypeのオプション名

### ISSUE THREAD

**Issue by masa0612** [project-hatohol/HAPI-2.0-Specification#16]
https://github.com/project-hatohol/HAPI-2.0-Specification#user-content-updatetype

現在はALL，またはUPDATEの2オプションがある。
しかしALLではなく，OVERWRITEであるべきかなぁと。

例えばfetchTriggerでホストを指定して送信してもらう際，オプションとしては
指定したホストに属するトリガーしか返さないにも関わらずALLオプションを使用することになります。
ここに違和感を感じてこのIssueを建てました。あまりユーザーライクな表現ではない気がします。

このALLという名称を変更するか否かを相談させてください。
また，変更すべきなら名前をどうするか提案していただけると嬉しいです。

**Comment by ashie** [comment]
今の名称は私もしっくりとはきていないのですが、代替案は思いついていません。
しかし、少なくともOVERWRITEでは無いと思います。
UPDATEでも既存のトリガーを上書きするのは同じなので。

> 例えばfetchTriggerでホストを指定して送信してもらう際，オプションとしては
> 指定したホストに属するトリガーしか返さないにも関わらずALLオプションを使用することになります。

指定したホストのALLということで一応意味は通るんじゃないかなと思います。

**Comment by masa0612** [comment]
たしかにそうですねぇ…
クローズしちゃいます
