### ISSUE TITLE
エラーに関する仕様が無い

### ISSUE THREAD

**Issue by ashie** [project-hatohol/HAPI-2.0-Specification#17]
JSON-RPCではエラー時にerrorオブジェクトを返すこととなっているが、HAPI-2.0にはエラーに
関する仕様がまだ無い。

サーバ側の実装で、エラー時の処理を実装しようとしたところではたと手が止まってしまった。

**Comment by kz0817** [comment]
F2Fで議論した際には、JSON-RPCで定義されるエラー（例：-32700    Parse error）に該当する場合、それを使用して、適当なものがない場合は、空いているコードにHAPI独自のエラーを追加するという方向性でした。

**Comment by masa0612** [comment]
@kz0817 さんのおっしゃるとおり、JSON-RPCで定義されるエラーに該当する場合はそれを使用して、空いているコードにHAPI独自のエラーを追加してゆきます。以前は仕様書にもHAPI独自のエラーコードをまとめるセクションを用意していたのですが、現状だとそのようなエラーが思い当たらなかったため、一時的に削除しています。

**Comment by masa0612** [comment]
仕様書にも

> 　情報交換の基本プロトコルとして，JSON-RPC 2.0を用います。 

とあることから、現状問題はないかと思います。実装していくにあたり必要なエラーが出てきた際はIssueを立てて議論することが好ましいと思います。

**Comment by ashie** [comment]
了解です。
