### ISSUE TITLE
TimeStampの要件の質問

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/HAPI-2.0-Specification#18]
`YYYYMMDDhhmmss.nnnnnnnnn` の形式と `unixtime` が `TimeStamp` に入れられるのでしょうか？
unixtimeでも仕様に合致するというのが読み取れませんでした。
https://github.com/project-hatohol/hatohol/pull/1208 を送ってしまって気づいたのですが、仕様ではナノ秒以下を省略できるとまでしか書かれておらず…。
YYYYMMDDhhmmss に変換できる数値ならば良いのでしょうか。（と言ってもunixtimeくらいしか思いつきませんが。。。）

**Comment by cosmo0920** [comment]
すいません、LastInfoのvalueの話だったので勘違いでした。クローズします。

**Comment by ashie** [comment]
一応口頭で話したことをメモしておきます。

LastInfoのvalueはプラグイン側が決めるので、サーバ側ではその形式には関与しない。
サーバ側はもらった文字列をそのままDBに保存するだけ。
