### ISSUE TITLE
serverTypeの追加手順の古い説明が残ったままになっている

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/HAPI-2.0-Specification#2]
詳細はserverTypeの節の説明を参照。

https://github.com/project-hatohol/HAPI-2.0-Specification#servertype

**Comment by masa0612** [comment]
これどうしましょう。
追加する必要はありますが，現状追加方法を説明しているドキュメントはないので
一旦削除するか，現状のままにしておくか。。。

**Comment by cosmo0920** [comment]
そうですねぇ。確かに追加する必要がありますね。
このIssueはServerTypesを追加するドキュメントの参照を追加する、
みたいなIssueとしておきましょうか？

**Comment by masa0612** [comment]
この記載は削除して，単にこのリポジトリにissue登録しておくのもありかもしれません。

**Comment by cosmo0920** [comment]
そうですね。そうしましょう。
