### ISSUE TITLE
updateTriggersプロシージャのlastChangeTimeの型

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/HAPI-2.0-Specification#20]
https://github.com/project-hatohol/HAPI-2.0-Specification#user-content-updatetriggersmethod にあるように今は `String255` となっていますが、時刻を扱うので `TimeStamp` 型にすることを提案します。
いかがでしょうか？

**Comment by masa0612** [comment]
I fixed it in 80d6a7dd0e21:)

**Comment by cosmo0920** [comment]
Thanks! Хорошо! XD
