### ISSUE TITLE
登録サーバー情報が更新されたことを通知するnotification

### ISSUE THREAD

**Issue by masa0612** [project-hatohol/HAPI-2.0-Specification#23]
掲題に挙げたものの必要性を感じています。

例えばポーリングを行っている最中にポーリング時間がWebUIから変更された時，
そのポーリング時間をプラグイン側で反映する必要があります。
このnotificationがあれば，
変更されたことを通知するnotificationを受け取る
↓
ポーリングを中止
↓
getMonitoringServerInfoで新しい登録サーバー情報（ポーリング時間）を取得
↓
ポーリングを再開する
という流れが可能になります。

HAPI1.0までにあったterminateコマンドとほぼ同様と考えて良いと思いますが，
この通知を受け取った際にどういった動作を行うかはプラグイン作者に委ねればよいため，
terminateという単語は好ましくありません。

このnotificationを実装するか否か，またその際の名前についてここで考えたいと思います。
意見が有る方はよろしくお願いします。

**Comment by ashie** [comment]
terminateと同様かというと、ちょっと違うと思います
- HAPI1.0ではプラグインの生き死にをサーバ側で管理していたので、単に再起動すれば良かった。
  (終了させるためにterminateがあった)
- HAPI2.0ではプラグインの生き死にを管理しないこととなった。ただし、便宜上起動および終了コマンドは登録できるようになった。

notificationを追加するのは一つの手ですが、
- UI側に「プラグインを再起動するまで設定は反映されません」と出すだけに止める
- 起動および終了コマンドが登録されている場合は、自動で再起動してあげる

というのも一つの手だと思います。

個人的にはnotificationはあった方がいいと思います。
起動時はともかく、設定変更時にも両方の操作が必要なのは面倒くさいので。

**Comment by ashie** [comment]
> 個人的にはnotificationはあった方がいいと思います。

プラグイン側で待ち受けが必要になると、前に #4 で言った実装の面倒臭さが気になるのですが、
よく考えたらAMQPでは普通のprocedurerの実装でもreplyの待ち受けが必要なので、結局両方
の実装が必要になるんですかね? だとしたらその問題も関係なくなると思います。

**Comment by masa0612** [comment]
> よく考えたらAMQPでは普通のprocedurerの実装でもreplyの待ち受けが必要なので、結局両方
> の実装が必要になるんですかね? 

notificationのため，そもそも待ち受け処理は必要ないのではないでしょうか。
その他のタイプがmethodのものは，レスポンスを返す必要があるので
Mandatoryにしてしまうと，レスポンスを返すという待ち受け処理が必須になってしまいますが，
notificationである以上，そもそも返すものがありません。

…という話ではない？あまり理解しきれていないので見当違いのことを言っていたらすみません。

**Comment by ashie** [comment]
しかし、UIでの登録項目は今のHAPIの登録画面とだいたい同じ感じになるんじゃないかと思いますが、
そうなるとAMQPのブローカーURLや静的キューアドレスも変わり得ることになります。
今の仕様ではサーバ側とプラグイン側で接続前にこれらを示し合わせておかなければいけないはずなので、
これらが変わったときの対応ができないと思います。

今の仕様のままでいくなら、やっぱりnotification加えない方がいいかも。

**Comment by masa0612** [comment]
となると

> UI側に「プラグインを再起動するまで設定は反映されません」と出すだけに止める
>     起動および終了コマンドが登録されている場合は、自動で再起動してあげる

この案が現実的ですね。Hatoholがプラグインの生死を管理できない以上，仕方がないことなのかも…

**Comment by ashie** [comment]
> notificationのため，そもそも待ち受け処理は必要ないのではないでしょうか。

notification受けるのはプラグインですよね?
返す以前に受けなきゃいけないわけですが、いつ来るかわからないんだからそれを待つために
スレッドなりなんなりが必要ですよね?

**Comment by masa0612** [comment]
> スレッドなりなんなりが必要ですよね?

理解しました。
そうですね，現状ではAMQPを通信路としているため，そもそも #4 が関係無かったということですね。

**Comment by ashie** [comment]
接続情報は除外して、それ以外の設定が変わった場合にはnotificationを投げるという手もありますけどね。

**Comment by masa0612** [comment]
それはいいかもしれませんね。要するに両方実装するということですよね。
手間は増えますが，使いやすさ的にそうしたほうが良い気がします。

**Comment by ashie** [comment]
接続情報も、切る前にnotification投げればいいのかな?

**Comment by masa0612** [comment]
Nice idea

**Comment by ashie** [comment]
（´-`）.｡oO（面倒臭いことから逃げるつもりがどんどん墓穴掘ってるな）

**Comment by masa0612** [comment]
（´-`）.｡oO（あ，これ埋まって戻ってこれないパターンだ）

**Comment by cosmo0920** [comment]
（´-`）.｡oO（通知って意外と面倒なんですね…。）

**Comment by ashie** [comment]
updateMontortingServerInfoという名前で監視サーバの情報(getMonitoringServerInfoのresponseと同じ形式)を投げる

**Comment by ashie** [comment]
> updateMontortingServerInfoという名前で監視サーバの情報(getMonitoringServerInfoのresponseと同じ形式)を投げる

上記補足: 6/11リアルミーティングでの合意事項

**Comment by masa0612** [comment]
#57 で追加した。
コレに関してはレビューをしていただきたいと思っています。
