### ISSUE TITLE
型が「String」のままの箇所が随所に残っている

### ISSUE THREAD

**Issue by ashie** [project-hatohol/HAPI-2.0-Specification#26]
「String」型は全て最大長を示すサフィックスが付いて、単なる「String」はなくなったものと
認識していますが、まだ随所に「String」のままのものが残っているようです。
備忘録のためにissueを立てておきます。

**Comment by ashie** [comment]
再度確認してみたところ、単なる「String」となっているところは無かった。
小文字の「string」となっているものは、別途文字列一覧が定義されているものなので、意図的らしい。
closeします。

**Comment by masa0612** [comment]
そうですね。
別途文字列定義されているため，String255のように型を定義しても意味が無いので
 JSON-RPC本来の型名であるstringを使用しました。
