### ISSUE TITLE
仕様書に載っているJSONを整形済みのものにしたい

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/HAPI-2.0-Specification#28]
アイディアの発端：https://github.com/project-hatohol/HAPI-2.0-Specification/pull/19#issuecomment-103378174
- [x] `jq` コマンドに仕様書のJSONを食べさせて出力結果を仕様書のJSONと置き換える。
  - [x] 整形できないJSONを修正する

**Comment by cosmo0920** [comment]
#30 にて `hostParent` 以外を整形してみました。 `hostParent` までJSONの整形が完了したらこのissueは完了です。

**Comment by masa0612** [comment]
hostParentsの修正も確認したためクローズします

**Comment by cosmo0920** [comment]
:+1:

**Comment by cosmo0920** [comment]
クローズし忘れですか？クローズしておきますね。

**Comment by masa0612** [comment]
／(^o^)＼
