### ISSUE TITLE
exchangeProfileの送信先プロセス名の取得方法

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/HAPI-2.0-Specification#29]
https://github.com/project-hatohol/HAPI-2.0-Specification#exchangeprofilemethod

リクエストとレスポンスの `name` 要素が両方「送信先のプロセス名」となっていますが、この送信先のプロセス名を知る方法が仕様書からは判断できません。

「送信先のプロセス名」はAMQPの接続を確立する時に取ってくるものなのでしょうか？
それとも、`exchangeProfile` プロシージャを介して「送信先のプロセス名」を交換するものなのでしょうか？

**Comment by masa0612** [comment]
すみませんほんとうにもう…ミスしか無い。。。

送信先 -> 送信元，なので
「exchangeProfileプロシージャを介して送信元のプロセス名を送り，送信先のプロセス名を取得する」
が想定している動作です。

**Comment by cosmo0920** [comment]
つまり互いに自分のプロセス名を送り合うという動作になるんでしょうか？

このプロシージャのプロセス名を交換する意図が読めません。
どのような意図があるんでしょうか。

**Comment by masa0612** [comment]
> 接続完了の旨を伝えるログなどに利用されます

とあるとおり，渡した後はお好きにどうぞ，といった想定で挿入されています。
サーバーが受け取ったプラグインのプロセス名はログに接続完了のメッセージと合わせて出力するようにする。
とリアルミーティングでありました。

**Comment by cosmo0920** [comment]
おぉ、ログに使うんですね。了解です。

**Comment by masa0612** [comment]
もしかしたら @ashie さんが居ない際のリアルミーティングで話したことだったかもしれないです。
伝達不足です。申し訳ない。

**Comment by ashie** [comment]
> もしかしたら @ashie さんが居ない際のリアルミーティングで話したことだったかもしれないです。
> 伝達不足です。申し訳ない。

たぶん居なかったのだと思います(居なかったことの方が多かったはずですし)が、居なくても仕様書を
読むとその意図が分かることが重要なのかなと思いました。そのための仕様書なので。

**Comment by cosmo0920** [comment]
このissueでの議論と https://github.com/project-hatohol/HAPI-2.0-Specification/commit/4d554d8288732c5e05179e0b896302882c9267f7 により仕様が把握できたのでクローズします。
