### ISSUE TITLE
エラーレスポンスの返し方の質問

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/HAPI-2.0-Specification#31]
resultのレスポンスが定められているプロシージャにおいて、エラーの場合は
- JSON-RPCに基づくエラーレスポンス
- Hatohol HAPI2.0に基づくエラーレスポンス

の２つのレスポンスが考えられます。
### Mandatoryになっているパラメータが足りなかった場合
- JSON-PRCに基づくエラーレスポンス
  - `JSON_RPC_INVALID_PARAMS(-32602)` 付きのJSONを返す
### Hatohol　Server側で問題が発生した場合
- resultに定義されているエラーレスポンス:

``` json
{
  "id": 1,
  "result": "FAILURE",
  "jsonrpc": "2.0"
}
```

上記の認識でいましたが、認識の相違はあるでしょうか？
### このIssueの完了条件
- [x] 認識の相違がなくなること
- [ ]  HAPI 2.0の仕様書に反映されること

**Comment by masa0612** [comment]
> 上記の認識でいましたが、認識の相違はあるでしょうか？

相違ありません。私もその認識です。
チェック項目「HAPI2.0の仕様書に反映されること」というのは、
相違があった場合に、その相違を無くし、反映させるということですよね？
創意がない現在、仕様書に反映することはないということでよろしいでしょうか。

**Comment by cosmo0920** [comment]
最後のが言葉足らずでしたね。すみません。 `Mandatoryになっているパラメータが足りなかった場合` の補足説明が書かれていなかったのでこのIssueを立てました。そのため、何らかの補足説明が欲しいです。

**Comment by masa0612** [comment]
あ～なるほど。理解しました。
つまり「2つのエラーレスポンスをどのように使い分けるか」を具体的に書くことが
今求められていることでしょうか？

**Comment by ashie** [comment]
そうですね。

**Comment by masa0612** [comment]
了解しました。
本当に申し訳ないのですが、正直こちらも手一杯なのですぐにドキュメントを修正することができません。
認識合わせは完了したので、そういった前提で進めていただいてもよろしいでしょうか？
手が空き次第、その他の修正もまとめて行う予定です。

**Comment by ashie** [comment]
はい、認識の確認さえできれば、仕様への反映は余裕ができてからでいいと思います。

**Comment by cosmo0920** [comment]
了解しました。

現時点で http://www.jsonrpc.org/specification#response_object の形式に沿っているのでこのRPCとセットで読めばなんとか誤解がない程度にはなっていると思います。
ただ、

``` json
{
  "id": 1,
  "result": "SUCCESS",
  "jsonrpc": "2.0"
}
```

のレスポンスに関することが強調され気味かな、と感じました。

**Comment by masa0612** [comment]
（´-`）.｡oO（実装がきつすぎてリリース日までにドキュメント整備が間に合う気がしない・・・）

**Comment by masa0612** [comment]
> レスポンスに関することが強調され気味かな、と感じました

すべてのリクエストRPCの例で記載していますからね。
確かにこの印象が強くなってしまっているとはおもいます。
1ヶ所にまとめれるとはおもうので、編集するときに修正するのもありかもしれません。

**Comment by ashie** [comment]
2015/06/11 リアルミーティングに、上記の認識に加えて下記追加:

exchangeProfileが完了しないていない状態でmethodが来た場合は、
JSON-RPCのエラーではなく、Hatohol形式のエラーを返す

``` json
{
  "id": 1,
  "result": "FAILURE",
  "jsonrpc": "2.0"
}
```

**Comment by masa0612** [comment]
#59 で修正した。
以上の修正でいかがでしょうか。不足点おっしゃっていただけると幸いです。

**Comment by ashie** [comment]
> Hatoholサーバーからfetchプロシージャ，またupdateMonitoringServerInfoプロシージャによるリクエストや通知が届いた場合は

単純に「他のプロシージャ」で良いと思います。

> Hatoholサーバーに返答しなければなりません。

「Hatoholサーバー」に限定しなくて良いと思います。

以上で、記述がシンプルになるし、サーバおよびプラグイン共通の記述になると思います。

**Comment by masa0612** [comment]
レビューありがとうございます！
上記を踏まえたPRを作成しました。 #61 

お手数ですが，再度レビューをよろしくお願いします。
