### ISSUE TITLE
fetchItemsとfetchTriggersの引数（hostIds）について

### ISSUE THREAD

**Issue by masa0612** [project-hatohol/HAPI-2.0-Specification#39]
現在は取得する各要素が属するホストを複数指定することが出来る仕様だが，
”全て”のホストを選択するときはどうすべきか考えていなかった。
考えられる手法は恐らく3つで
- hostIdsをOptionalにし，hostIdsがparamsに存在しない場合は，全てのホストに属するアイテム，トリガーを取得する
- hostIdsに配置する値を新たに定義する。 ex. hostIdsの値に”ALL”が入っていた場合は全てのアイテム，トリガーを取得する…など
- hostIdsをOptionalにし，さらに追加のOptional要素の”All”を加える。これはBool値を入れることができ，Trueならば全てのトリガー，アイテムを取得する。上2つのハイブリッド？

プラグインの実装的にはどちらでも手間は大差ないとおもいます。
個人的には１つ目のほうが好ましいと思っています。hostIdsを指定すれば，範囲を絞れる。指定しなければ全て。とすっきりしているのではないかと

**Comment by ashie** [comment]
確かに今の仕様だとMandatoryになってますね。
それに気がついてなかったので

> hostIdsをOptionalにし，hostIdsがparamsに存在しない場合は，全てのホストに属するアイテム，トリガーを取得する

勝手にこれだと思ってました。
これが良いと思います。

他の2つについては

> hostIdsに配置する値を新たに定義する。 ex. hostIdsの値に”ALL”が入っていた場合は全てのアイテム，トリガーを取得する…など

監視サーバ側でどんなID定義になっているかわからないので、特定の文字列に特定の役割を持たせるのは危険です。

> hostIdsをOptionalにし，さらに追加のOptional要素の”All”を加える。これはBool値を入れることができ，Trueならば全てのトリガー，アイテムを取得する。上2つのハイブリッド？

冗長だと思います。

**Comment by masa0612** [comment]
#40
修正しました

**Comment by masa0612** [comment]
それではこの仕様にプラグイン側も修正しておきます

**Comment by ashie** [comment]
#40 で修正した。
