### ISSUE TITLE
HAP側プロシージャはすべてoptionalの方がよいのでは

### ISSUE THREAD

**Issue by ashie** [project-hatohol/HAPI-2.0-Specification#4]
exchangeProfileはHAP側でもMandatoryとなっていますが、これはどのような使用方法を想定していますか?
(たぶんサーバ側の再起動を想定したものだと思っていますが。)
出来れば、HAP側のプロシージャはすべてoptionalの方がよいと思っています。
一つでも実装しなければならないプロシージャが存在すると、サーバー側から待ち受け処理を実装しなければ
いけないことになり、プラグインの実装の難易度・面倒くささが一気に上がってしまうためです。
(それなりの応答性が求められるのであれば、たぶん非同期処理なりマルチスレッド・マルチプロセスなりが
ほぼ必須)

サンプル実装を作っみた後の感触にもよるかと思いますが、プラグイン側プロシージャが無くて済むなら
それに越したことはないと思います。

**Comment by masa0612** [comment]
仮にexchangeProfileが実装されていなかったとしても動作に不備は起こる可能性は低いと思いますし、
Optionalにしてしまっても問題ないと思います。
@kz0817 さんはどうおもいますか？

**Comment by kz0817** [comment]
ashieさんの主張はもっともです。そうしないとHatohol-senderのようなツールもつくれないですね。不都合が発生しないとは言い切れませんが、仕様をそう変更して、問題がある場合には、別のフォローを考えましょう。

**Comment by masa0612** [comment]
masterに反映させました。

**Comment by ashie** [comment]
以後の話し合いで、exchangeProfileはやはりMadatoryであった方がよいという話になった
- 最初にexchangeProfileが完了するまで通信を行わないのが本仕様の前提
- サーバ側が再起動したとき、サーバ側からexchangeProfileを投げなければならない ((plugin側procedureが必要)
- プラグイン側procedureを全てをOptionalにしても、結局サーバ側procedureを実行したときのresponse待ちでlistenは必要
- イベントを投げつけるだけのような簡易な実装にしたい人向けには、他のプロセスからの受信専用のHAPを用意して、そこに投げさせればよい

**Comment by ashie** [comment]
2015/06/11のリアルミーティングにて:
- pluginのexchangeProfileはMandatoryとする

**Comment by ashie** [comment]
そのように修正した
