### ISSUE TITLE
fetchEventsのcount

### ISSUE THREAD

**Issue by ashie** [project-hatohol/HAPI-2.0-Specification#41]
2015-06-11 リアルミーティングにて:

fetchEventsの"count"は1000件までとなっているが、返す件数はプラグイン側で
勝手に減らして良く、あくまでもコールする側(サーバ側)の都合となるため、
1000件に制限する必要は無いのではないか?という議論があった。

ただ、結論がどうなったのか足永の記憶・記録が定かではない。

countは現状MandatoryになっているのをOptionalにしてもよいのではないか?
という議論もあったが、こちらはMandatoryのままという結論となった。

**Comment by masa0612** [comment]
仮に制限を無くした場合は，プラグイン側から実質上限なく一度にイベントを送ることができます。
制限は付けておいたほうが良いのではないでしょうか。制限を外す意義も薄いと思われます。

**Comment by ashie** [comment]
私も、わざわざ外すことも無いと思います。
closeしちゃいます。

**Comment by masa0612** [comment]
Thank you for your 同意
