### ISSUE TITLE
updateTypeにFETCHEDを加える

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/HAPI-2.0-Specification#42]
fetchTriggerに起因するputTriggerにおけるupdateTypeは、ALLでもUPDATEDでもない気がする。
FETCHEDとか、SELECTEDとかを追加すべき。

**Comment by ashie** [comment]
すみません、違いが理解できませんでした。

**Comment by kz0817** [comment]
fetchTriggersでは、hostIdsの指定が必須です。
このメッセージの受信を契機に、プラグインは、triggerを取得してputTriggersを
コールします。
そのパラメータのupdateTriggersはMandatoryですので、ALLかUPDATEDを
指定することになると思いますが、どちらも適さないと思いました。
解釈というか、定義の問題になるかもしれませんが、ALLが、すべてのホストの
トリガーという意味で用いられると、明らかにおかしいです。fetchTriggersに起因
する場合は、指定されたもの「全て」と定義されれば、それでもいい気がしますが、
コンテキストによって、意味が変わるのも、複雑な感じがしました。

**Comment by ashie** [comment]
> fetchTriggersでは、hostIdsの指定が必須です。

これは #39 でOptionalにしようという議論がありましたが、MandatoryかOptionalに関係なく、
確かにhostIdsが指定された場合は ALL でも UPDATED でもないですね。
理解できました。

**Comment by masa0612** [comment]
これ一度 #16 で議論されていますね。
その際はALLでも一応意味は通るということでクローズになりました。
確かに変えるべきだとは思うのですが，かなり優先度は低いと思います。
15.06ではまずは動くとこまで各プラグインの実装を行い，
それらが終わってから（もしくは15.09）でFETCHEDという実装にするのはどうでしょうか。

**Comment by ashie** [comment]
> これ一度 #16 で議論されていますね。

完全に忘れてました...

**Comment by kz0817** [comment]
そういう定義にしましょう。慣れという部分もあるので。クローズします。
