### ISSUE TITLE
itemオブジェクトにvalueTypeが無い

### ISSUE THREAD

**Issue by ashie** [project-hatohol/HAPI-2.0-Specification#43]
現在のHatoholの実装にはItemInfoにvalueTypeというメンバーがありますが、
本仕様にはこれが無いようです。

このメンバーを無くしたのには何か理由がありますか?
(例えばvalueの形式から推測できるとか?)
あるいは単に入れ忘れただけでしょうか?

**Comment by masa0612** [comment]
これ確か場所は忘れましたけど、どこかで議論した記憶があります。
その時の結論ではvalueTypeメンバは無くしてプラグイン側で判断するといったないようであったと記憶しています

**Comment by ashie** [comment]
> その時の結論ではvalueTypeメンバは無くしてプラグイン側で判断するといったないようであったと記憶しています

WebUIで使ってるので、どちらかと言えばWebUIで判断が必要な気がします。
（プラグイン側では単に文字列にして詰めれば良い）

WebUIの方を直せということなのかな? 現状の使われ方を見ると、lastValueが判断出来る形で常に詰まって
いるのであれば(数値かどうか、floatかintか)、確かに何とかなるのかなぁと思いました。

**Comment by ashie** [comment]
現在の実装に関してはvalueTypeが無くても何とかなりそうなので、無くす方向で。

**Comment by ashie** [comment]
> 現在の実装に関してはvalueTypeが無くても何とかなりそうなので、無くす方向で。

「概ね」を付けようと思って忘れてた。
型を推測はしないといけないのは確かなので、完全に解決できるわけではない。
が、実用上特に問題は無いと思う。

**Comment by ashie** [comment]
> その時の結論ではvalueTypeメンバは無くしてプラグイン側で判断するといったないようであったと記憶しています

現在の実装でvalueTypeを追加した理由を思い出した。
ZabbixではvalueType毎にテーブルが分かれていて、Historyを取得するときに
呼出側が正しいvalueTypeを指定しないとHistoryを取得することができない。
毎度Itemを取得してvalueTypeを確認するのはレスポンスが悪いので、Hatohol
側で保管するようにしたのだった。

**Comment by ashie** [comment]
> WebUIで使ってるので、どちらかと言えばWebUIで判断が必要な気がします。

と言いましたが、前言撤回。

> 毎度Itemを取得してvalueTypeを確認するのはレスポンスが悪いので、Hatohol
> 側で保管するようにしたのだった。

つまり、この辺頑張るところをプラグイン側に実装しないといけない

**Comment by ashie** [comment]
> つまり、この辺頑張るところをプラグイン側に実装しないといけない

今のHAPI2プラグインの実装を覗いてみましたが、既に実装されていますね。

**Comment by masa0612** [comment]
クローズした後の理由だったと私も記憶していたため、そのように実装しました。
ZabbixのAPIではfetchHistoryがコールされた際、指定されたアイテムIDのアイテム情報を取りに行き、valueTypeを取得した後にヒストリーを取りに行くように実装しています。

**Comment by ashie** [comment]
一回辺りのHistoryの取得時間がほぼ2倍に増える(HTTPリクエストが2回になる)ので複数回Historyを
取得しなければならないときのレスポンスが気になるが、現状でも速いわけではないので、根本的に
頑張り方を見直さないといけない(trendを取得できるようにするとか)
