### ISSUE TITLE
MonitoringServerInfoの中のtypeについて

### ISSUE THREAD

**Issue by masa0612** [project-hatohol/HAPI-2.0-Specification#44]
現在，pythonでプラグインを作成しているのですが，そのプラグイン内において
typeをserver_typeと名づけて使用している。

本来であれば，ドキュメントに合わせてtypeと名づけたいところなのですが，
typeは予約語ではないものの組み込み関数で定義されているため，あまり好ましくないと感じている。
ただMonitoringServerInfoオブジェクトの中で完結する変数のため，本来のtype関数の阻害をするわけではない。

動作に問題がなければドキュメントのtypeに合わせてMonitoringServerInfoオブジェクトではtypeと書くのか，
それともこのHAPIの仕様自体が被りを避けるような名前付けをすべきなのか，判断できなかったためIssueをあげました。

個人的には被ってしまっても問題ないと感じているので，現状維持で良いかなとは思っています。

**Comment by masa0612** [comment]
うまく説明できている気がしないので，ガンガン突っ込んでください

**Comment by ashie** [comment]
仕様としては変える必要はないです。
- "MonitoringSeverInfo"というコンテキストでの"type"なので、"server"を付けるのは冗長(”server”以外の何か別のtypeを表しているのであれば、プレフィックスを付ける必要があるが)
- よほどの事情が無い限り、特定言語・特定実装の事情に振り回されるべきではないし、今回の場合は実装側でも特に問題があるわけでも無い。

**Comment by masa0612** [comment]
ありがとうございます。
