### ISSUE TITLE
TimeStampとして空文字列は許容されるのか?

### ISSUE THREAD

**Issue by ashie** [project-hatohol/HAPI-2.0-Specification#45]
TimeStampとして空文字列は許容されるのかという疑問が生じました。

現在、サーバ側実装とプラグイン側実装の結合テストを手元で進めています。
その際、Zabbixの設定が正しくなかったためプラグインがZabbixと接続できず、
putArmInfoのlastSuccessTimeに空文字列をセットして送出してきました。

lastSuccessTimeはMandatoryですが、セットすべきlastSuccessTimeは存在し
ないわけですから、納得はできる動作です。

一方、サーバ側ではTimeStampに空文字列が来ることを許容していないため、
エラーを返してしまいます。仕様としてはTimeStampのフォーマットは決まっており、
空文字列はこの仕様に準拠していないわけですから、こちらも現状では納得できる
動作です。

とはいえこのままでは動かないので、仕様を修正する必要があると思います。

解決方法としては以下のいずれかが考えられます。
1. TimeStampで空文字列を許容する定義を追加する
2. TimeStamp型を使用する個々のパラメータで空文字列の場合の動作を規程する
3. putArmInfoのlastFailureTimeやlastSuccessTimeをoptionalにする(セットできる値が無い場合)

個人的には2かな?と思っています。

**Comment by ashie** [comment]
一通り確認したが、セットできない可能性があるTimeStampはputArmInfoのlastSuccessTimeとlastFailureTimeだけかなと思った。そこに記述を追加してプルリクを投げる。

**Comment by kz0817** [comment]
> 一通り確認したが、セットできない可能性があるTimeStampはputArmInfoのlastSuccessTimeとlastFailureTimeだけかなと思った。そこに記述を追加してプルリクを投げる。

上記2.案を実現するための「確認」ですよね。よろしくお願いします。

**Comment by ashie** [comment]
#51 で修正
