### ISSUE TITLE
putHistoryのhistroiesをsamplesに変えてはどうか？

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/HAPI-2.0-Specification#47]
個々の要素を、sample (標本)と呼ぶがしっくりくる。
今のネーミングだと、要素をhistoryと呼んでいると感じる。
なお、sampleの集合がhistoryというのは、合点がいく。

**Comment by ashie** [comment]
たしかにそのほうがいいですね。

**Comment by kz0817** [comment]
このタイミング(HAPI2.0の正式リリース前にやるか？）、その時間的余裕はあるのか？
ashieさんの考えはどうですか？

**Comment by ashie** [comment]
HAPI 2.0のサーバ側の実装を変更するのはすぐできます。
REST API、グラフ機能まで波及させるかどうかは迷うところですが、やるならば一気にやってしまってほうが
いいと思います。REST APIでは"history"という単数形に配列を詰めています。

**Comment by kz0817** [comment]
じゃあ、やりましょう。

**Comment by ashie** [comment]
了解です

**Comment by kz0817** [comment]
commit mailにも返信しましたが、あやまって、改変したパッチを直接masterにpushしました。

**Comment by ashie** [comment]
じゃあもうcloseで...
