### ISSUE TITLE
URLの長さ

### ISSUE THREAD

**Issue by ashie** [project-hatohol/HAPI-2.0-Specification#5]
https://github.com/project-hatohol/hatohol/pull/1196 より

URLの長さが255なのは短すぎるかもしれない。検討が必要か?

ほとんどのケースでは足りるとは思うし、古い実装では255に制限されていたこともあるので255が
無難という考え方もあるが、いまどき255に制限されている実装を対象とするのも時代遅れかもしれ
ない。

現在の実装での短めの制限の例としては、IE11が2083文字らしい。
(ただし単純にあらゆる場面で2083というわけでもない: http://blogs.msdn.com/b/ieinternals/archive/2014/08/13/url-length-limits-in-internet-explorer.aspx)

**Comment by masa0612** [comment]
そもそもの話，URLをきちんと定義しないことには話は始まらないと思います。
どういったものを想定するかによって必要とされる長さも変わってきます。

プラグイン作成に当たってそろそろ決めないといけないですし，一度リアルミーティングを行いましょう。

**Comment by ashie** [comment]
> そもそもの話，URLをきちんと定義しないことには話は始まらないと思います。

参考までに過去にあった話から私の認識を書いておこうと思ったのですが、その前に...
自分の認識を説明をするためにgetMonitoringServerInfo()の項を確認していたのですが、
いくつか別のことに気がつきました。

https://github.com/project-hatohol/HAPI-2.0-Specification#getmonitoringserverinfomethod
- IPアドレスとかportとかって無くなったんですね
  - そういう方針であれば特に異論なし（そういう方針になったということで間違い無いでしょうか?という確認）
  - しかし、レスポンス例にはIPアドレスやポートが残っているようです。これは修正漏れ?
- 一方でdbNameが残っているのは意図的という認識で間違いない?
  - IPアドレスやポートはURLで表現できるが、dbNameは表現できないので残したという認識。

**Comment by masa0612** [comment]
> IPアドレスとかportとかって無くなったんですね 

おっしゃるとおりURLに含めます。例は修正する必要がありますね…ありがとうございます。

> 一方でdbNameが残っているのは意図的という認識で間違いない? 

どこまでURLに含めるか，という点において私もはっきりと認識しているわけではないため，
それも含めて改めて話す必要があります。すみません。

**Comment by masa0612** [comment]
> それも含めて改めて話す必要があります。

話す必要はない気がしてきました。
結局のところ，URLに何を含めるかはプラグインが定義するものなので，
作者に丸投げでいいですね。

dbNameに関してなのですが，これもURLに含めてしまっていいと思うので削除します。

**Comment by kz0817** [comment]
>  dbNameに関してなのですが，これもURLに含めてしまっていいと思うので削除します。

これには、反対です。
たしかに、URLの書式はプラグイン依存ではありますが、一般に
DBを含むURLはないからです（RESTのパスやクエリパラメータを除く）

ポートやプロトコルは、URLに含まれることが多いので、それらの
パラメータをURLに取り入れました。

プラグインの自由といってもコモンセンス（結局主観によるので
曖昧なのですが）が、維持されている必要があると思います。

**Comment by masa0612** [comment]
なるほど。
ではextendInfoに含めるのはどうでしょうか。
dbNameに限らず，監視対象にアクセスする情報は全てextendInfoに含めてしまったほうが良いと思いました。
具体的には
- userName
- password
- dbName

場合によってはユーザー名やパスワードが不必要な監視対象もあるかもしれませんし。

それと見返していて疑問に感じたことが出てきました。
serverIdとnickNameの情報はプラグインに必要かどうか，ということです。
この２つの情報の利用手段がわからないのですが，想定される必要なケースはあるでしょうか。
もし無いのであればこちらも削除して良い気がします。

**Comment by kou** [comment]
> 一般にDBを含むURLはないからです（RESTのパスやクエリパラメータを除く）

参考になるかわかりませんが、RDBMSへの接続情報をURLで表現するときはデータベース名を含めることができる場合が多いです。

例えば、JDBCを使うときはデータベース名を指定できます。

MySQL: http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html

``` text
jdbc:mysql://[host][,failoverhost...][:port]/[database] »
[?propertyName1][=propertyValue1][&propertyName2][=propertyValue2]
```

PostgreSQL: https://jdbc.postgresql.org/documentation/94/connect.html

``` text
jdbc:postgresql:database
jdbc:postgresql://host/database
jdbc:postgresql://host:port/database
```

また、RailsでもURLでデータベースを指定できます。

http://www.rubydoc.info/docs/rails/4.1.7/ActiveRecord/ConnectionAdapters/ConnectionSpecification/ConnectionUrlResolver:initialize

``` text
url = "postgresql://foo:bar@localhost:9000/foo_test?pool=5&timeout=3000"
ConnectionUrlResolver.new(url).to_hash
# => {
  "adapter"  => "postgresql",
  "host"     => "localhost",
  "port"     => 9000,
  "database" => "foo_test",
  "username" => "foo",
  "password" => "bar",
  "pool"     => "5",
  "timeout"  => "3000"
}
```

**Comment by ashie** [comment]
ちなみにアドレスやポートがなくなると、ArmNagiosNDOUtilsをHAPI2.0にしたときにこれらをどう
入れるのかちょっと気になった。接続先はMySQLになると思うが、mysqlを表すオフィシャルな
schemeは無いと思うので（アンオフィシャルなものとしてはjdbc:mysqlというのがあるようだ）。

ほとんどのパラメータは結局プラグイン側で自由に使ってよいという方針だと思うので、実装の
選択肢は色々ある。
- jdbc:mysqlを使う
- 独自のschemeを定義する
- extendedInfoに入れる

**Comment by ashie** [comment]
> 参考になるかわかりませんが、RDBMSへの接続情報をURLで表現するときはデータベース名を含めることができる場合が多いです。

注) 前コメントはこれ読む前に書きました

**Comment by kz0817** [comment]
> 参考になるかわかりませんが、RDBMSへの接続情報をURLで表現するときはデータベース名を含めることができる場合が多いです。

なるほど、参考情報ありがとうございます。

> extendedInfoに入れる

これに一票。パラメータは、監視システムによって様々なので、ここにまるっと入れるというが慣例としては、わかりやすいと思います。

**Comment by ashie** [comment]
> 結局のところ，URLに何を含めるかはプラグインが定義するものなので，
> 作者に丸投げでいいですね。

結局のところ、私が説明しようとしていた私の認識もこれです。

**Comment by masa0612** [comment]
kouさんの参考情報を見て思ったのですが，
extendInfoとURLの差はあるのでしょうか。
全てextendInfoという括りでまとめてしまって良いと感じたのですがいかがでしょうか。
（＝URLを削除する）

> dbNameに限らず，監視対象にアクセスする情報は全てextendInfoに含めてしまったほうが良いと思いました。
> 具体的には
> 
> ```
> userName
> password
> dbName
> ```
> 
> 場合によってはユーザー名やパスワードが不必要な監視対象もあるかもしれませんし。

また，これについて何か意見をいただけますと助かります。

**Comment by masa0612** [comment]
> serverIdとnickNameの情報はプラグインに必要かどうか，ということです。

こちらについてもご意見いただけますと幸いです。

**Comment by ashie** [comment]
最初の頃の議論で
- serverIdとnickNameを除いて、どのパラメータを具体的にどのように使用するかはプラグインの実装に任せる
- とするとextendedInfoに全て入れるという選択もありうるが、よく使用されるであろう典型的なパラメータは定義しておく
  - UIで登録した監視サーバのリスト表示するときなどは、ある程度形式化された情報が無いとユーザーが見ても識別できない恐れもあるため

というような話がありました。
この観点から、URLはあった方がよいと考えています。

**Comment by ashie** [comment]
userNameやpasswordも、監視サーバにアクセスするためには通常は何らかの認証がある
だろうという観点から、典型的な情報と考えて、今のまま有ってよいのでないかと思います。

dbNameは、かなり主観的な意見になりますが、監視システムのDBに直接アクセスするのは
できるだけ避けたい(監視システムが提供するAPIでデータを取得したい)という観点から、
消してしまった方がよいような気がしています。

**Comment by ashie** [comment]
> serverIdとnickNameの情報はプラグインに必要かどうか，ということです。
> こちらについてもご意見いただけますと幸いです。

Hatoholサーバしか知らない情報はなるべく全部渡してあげたほうがよいと思います。

**Comment by masa0612** [comment]
改めてコミットしました

**Comment by Mnakagawa** [comment]
ミス。まだコミットしてないです

**Comment by masa0612** [comment]
URLの長さについてが本来のissueでした。
今までの議論から，「URL」にはURL，IPアドレス，ポートを含むことを前提として話を進めていきます。

@kz0817 さんは https://github.com/project-hatohol/hatohol/pull/1196 内にて

>  255 characters for URL may be a little small for some case.

 とおっしゃっていますが，具体的にはどういったケースでしょうか。
自分の中でパッと想像できませんでした。

**Comment by kz0817** [comment]
> とおっしゃっていますが，具体的にはどういったケースでしょうか。
> 自分の中でパッと想像できませんでした。

単純に、FQDN部やパスが長いケースです。FQDN部は255文字まで許容されますし、パス部もファイルシステムを（ほぼ）そのまま反映するなら1000文字程度になる可能性があります。
また、上記の議論では、データベース名などのパラメータは、extendedInfoに格納しようという流れですが、プラグインの作者によっては、実装上の便宜から、それらのパラメータをURL内のクエリパラメータとして指定するかもしれません。

**Comment by masa0612** [comment]
なるほど。
IEでは2038文字だそうですが、それに習って同じ文字数で良いでしょうか

**Comment by kz0817** [comment]
> IEでは2038文字だそうですが、それに習って同じ文字数で良いでしょうか

そうですね。最近の主流なブラウザと同程度にしておくのが無難だと思います。
ただ、2038は、なんか中途ハンパな感じがします。2048がいいですね。
理由がなにかあるのかな？

**Comment by ashie** [comment]
私も2048で異論ありません。

**Comment by ashie** [comment]
いや、他とそれっぽく合わせるなら2047?

**Comment by masa0612** [comment]
確かに他の値に合わせるなら2047です。了解しました。

**Comment by masa0612** [comment]
Fixed in 76c0331a5c63bd3dbf90298befcfb9913cf87e01
