### ISSUE TITLE
Last EventをHatoholサーバから取得するRPCがあったほうがよい。

### ISSUE THREAD

**Issue by kz0817** [project-hatohol/HAPI-2.0-Specification#50]
Pluginが差分のみを送付するために、last infoという概念をHAPIに追加した。
ただ、なんらかの理由でそれが破損すると、Pluginだけでそれを修復する方法がない。

また、Ceilometer pluginでは、各alarm (trigger)ごとに最終イベントの時刻を
last infoとして保持しているが、alarmの数が増えると、last infoのサイズが増加
していく。いずれ、最大長の32767を超える。

ただ、なければ、動作しないわけではないので、HAPI 2.1で導入を検討か。

**Comment by masa0612** [comment]
リアルミーティングで不要との結論が出たため，クローズします。

**Comment by kz0817** [comment]
ミーティングでは、lastInfoが破損した場合、それを修復するためのツールを提供すべきという結論になりました。プラグインが自発的に修復することはしません。

**Comment by masa0612** [comment]
補足説明ありがとうございます！
