### ISSUE TITLE
各params表の語尾が統一されていない

### ISSUE THREAD

**Issue by ashie** [project-hatohol/HAPI-2.0-Specification#53]
ですます調とである調の両方が存在していてどちらに統一すると良いのかわからない

**Comment by masa0612** [comment]
ですます調がいいとおもいます

**Comment by ashie** [comment]
たしかに全体の調子を見るとですます調の方がいいかなと思っていました。
統一は後でやるとして、直近で修正したい箇所はですます調で修正していきます。

**Comment by masa0612** [comment]
お手数おかけします。よろしくお願いします。

**Comment by ashie** [comment]
あと句点(。)を付けるか付けないかの判断も迷った。
文章になっているところもあるので、付ける方で統一した方が良いのか?

**Comment by masa0612** [comment]
私は表の中では付けないように，それ以外では付けるようにしていました。
ただ付ける方で統一したほうがいいと思います。
