### ISSUE TITLE
MonitoringServerInfoプロシージャの仕様についての質問

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/HAPI-2.0-Specification#6]
https://github.com/project-hatohol/HAPI-2.0-Specification#getmonitoringserverinfomethod にて、

例として、

``` json
{
  "id": 1,
  "result": {
    "extendedInfo": "exampleExtraInfo",
    "serverId": 1,
    "url": "http://example.com:80",
    "type": 0,
    "nickName": "exampleName",
    "userName": "Admin",
    "password": "examplePass",
    "pollingIntervalSec": 30,
    "retryIntervalSec": 10
  },
  "jsonrpc": "2.0"
}
```

が挙げられているが、paramsに引数を渡さない仕様になっている。
そのため、欲しい監視サーバーをサーバー側で判断する情報が不足している。

従って、この仕様ではresultには複数の監視サーバーの情報が入っていると考えるのが自然だと思われる。

以上を反映すると、result以下のJSON要素は、
例えば`servers` などから始まる配列にした方が良いのではないだろうか。

``` json
{
  "id": 1,
  "result": {
    "servers": [
      {
        "extendedInfo": "exampleExtraInfo",
        "serverId": 1,
        "url": "",
        "type": 0,
        "nickName": "zabbix-vm",
        "userName": "Admin",
        "password": "zabbix",
        "pollingIntervalSec": 60,
        "retryIntervalSec": 10
      },
      {
        "extendedInfo": "exampleExtraInfo",
        "serverId": 2,
        "url": "",
        "type": 2,
        "nickName": "zabbix-hapi",
        "userName": "Admin",
        "password": "zabbix",
        "pollingIntervalSec": 30,
        "retryIntervalSec": 10
      }
    ]
  },
  "jsonrpc": "2.0"
}
```

**Comment by cosmo0920** [comment]
プラグインからどの監視サーバーが必要かという情報がサーバーから取れれば上の仕様でなくても良く、
例えばparamsに情報を取ってきたい監視サーバーの情報を渡せるようにすれば良さそうです。
（どれを渡すようにするかは別途考える必要あり）

**Comment by ashie** [comment]
現状のアクティブモードでは、プラグインを起動する際にAMQPのqueueの名前を環境変数を与えている。
MonitoringServer毎に別々のqueueを使用しているため、どのMonitoringServerInfoを使用すべきかを
同定することができている。

パッシブモードでは、サーバ側とプラグイン側がそれぞれ予めqueueの名前を設定することを前提としている
（静的キューアドレス）。

つまり、経路を開く段階で既にお互いがどの経路を使うべきかを知っているというのが現状の仕様。

HAPI2.0でも、経路確立の段階で既にお互いを同定できる状態となっていることを前提として、json-rpcの
仕様には含めないということでしょうか?

**Comment by ashie** [comment]
リアルミーティングであった話としては、HAPI2.0ではパッシブモードのみとなり、プラグインの起動や終了は
- Hatoholサーバはこれまでのように頑張ってプラグインプロセスを立ち上げたりしない。ユーザーが自分でサービスを立ち上げる。
- Web UIで起動コマンドと終了コマンドを登録できるようにして、これが存在する場合はHatoholサーバで実行してあげる

という形にしようという話がでていた。この場合、プラグインのコマンドラインオプション（あるいは設定ファイル）
でサーバIDなり静的キューアドレスなりをユーザーが渡す必要がある。

json-rpcの外側の話なのかもしれないが、そうであったとしても何かしらこの仕様でも言及してあげないと
プラグインを作る人が困ってしまう(プラグイン作れない)ように思う。

**Comment by masa0612** [comment]
> HAPI2.0でも、経路確立の段階で既にお互いを同定できる状態となっていることを前提として、json-rpcの
> 仕様には含めないということでしょうか?

おっしゃるとおりです。私もその認識です。
経路確率の段階でお互いを識別できる状態のため、getMonitoringServerInfoを受け取ったHatoholサーバーは
そのコマンドを受け取ったキューの名前から、そのコマンドを送信したHAPを特定し
対応したMonitoringServerInfoを返す事ができる、と考えていました。

> json-rpcの外側の話なのかもしれないが、そうであったとしても何かしらこの仕様でも言及してあげないと

確かにその通りです。ドキュメントを修正しておきます（すぐには無理だとは思いますが。。。）

**Comment by ashie** [comment]
> 確かにその通りです。ドキュメントを修正しておきます（すぐには無理だとは思いますが。。。）

通信経路を抽象化するという話もあるので、通信経路の仕様が決まらないと何も書けないと思うので、
しばらくペンディングですかね。現在、サーバ側でAMQPの実装を拡張しつつ検討中です。

**Comment by masa0612** [comment]
#60 で説明を加えました。
レビューをよろしくお願いします。

**Comment by cosmo0920** [comment]
:+1:

**Comment by fuguman** [comment]
はじめまして、池上と申します。
日本仮想化技術株式会社 
OpenStack構築手順書 Mitaka版
バージョン：1.0.0-b4 (2016/06/09作成)のhatohol導入手順
"https://github.com/virtualtech/openstack-mitaka-docs/blob/master/OpenStackMitaka.md"に従い、
HatoholにHAP2のZabbixプラグインまで、無事に行ったのですが、
「Hatohol」ダッシュボードの監視サーバータイプに「Zabbix (HAPI2)」ではなく「JSON(HAPI)」しか
表示されません。
コマンドラインで登録を試みると、「サーバタイプが見つからない」といったレスポンスとなります。
HAPI2プラグイン前のdb初期化手順のパスワードが「password」になっていたのですが、

# そのあたりが誤っているのでしょうか？

curl -d 'user=Admin' -d 'password=hatohol' http://10.0.1.138:33194/login
{"apiVersion":4,"errorCode":0,"sessionId":"33751bc9-4565-4503-a170-5426a4cf8734"}[root@hatohol hatohol]#
[root@hatohol hatohol]# curl -H 'X-Hatohol-Session:33751bc9-4565-4503-a170-5426a4cf8734' -d 'type=7' -d 'uuid=8e632c14-d1f7-11e4-8350-d43d7e3146fb' -d 'nickname=zabbix' -d 'pollingInterval=30' -d 'retryInterval=15' -d 'userName=Admin' -d 'password=zabbix' -d 'baseURL=http://10.0.1.133/zabbix/api_jsonrpc.php' -d 'passiveMode=false' -d 'brokerUrl=amqp://hatohol:hatohol@localhost/hatohol' http://10.0.1.138:33194/server

# {"apiVersion":4,"errorCode":56,"errorMessage":"The server type doesn't exist."}[root@hatohol hatohol]#

**Comment by fuguman** [comment]
申し訳ございません。池上でございます。問題が解決しましたので報告いたします。
先ほどの手順の13-4-4　HAP2のZabbixプラグインの導入前に13-4-3 HAPI2の追加で、
hatohol-db-initiator --db-user root --db-password password　を実行結果をログで確認したところ、

# 最終行に

If you want to drop the existing table and load data, use -f or --force option.
Succeessfully loaded: /usr/bin/../share/hatohol/sql/90-server-type-hapi-json.sql

# [root@hatohol ~]# systemctl restart hatohol

# JSON.sqlしかなかったため、実行手順もれかと思い再度じっこうしたところ、以下の様になり、

Succeessfully loaded: /usr/bin/../share/hatohol/sql/90-server-type-hap2-zabbix.sql
Succeessfully loaded: /usr/bin/../share/hatohol/sql/90-server-type-hapi-json.sql
[root@hatohol hatohol]# date

# Sun Jun 12 10:00:35 JST 2016

結果、「hatohol」の監視サーバ追加画面で、監視サーバタイプに『Zabbix (HAPI2)』が表示でき、
Zabbixサーバへの接続もOKになりましたので報告致します。

**Comment by masa0612** [comment]
はじめまして。中川と申します。
解決したようで何よりです！

上記ドキュメントを参照しましたが，13-4-3と13-4-4の手順が逆ですね。
HAP2をyumコマンドでインストールした後にhatohol-db-initiatorを実行しなければ
HatoholにHAP2を追加することはできません。
