### ISSUE TITLE
Create HAPI-2.0 Specification tag

### ISSUE THREAD

**Issue by masa0612** [project-hatohol/HAPI-2.0-Specification#77]
仕様もある程度固まり，プラグイン作成やサーバーも滞りなく進んでいます。
このあたりで仕様書をFixし，tagを付けるべきと考えたので議論しましょう。

RevisionとVersionを別々に管理するのか，それともまとめて ”1.v.r” のように，まとめるか。
意見をお聞かせください。個人的にはまとめたほうが今風な感じでいい気もしています。

また，tagの付け方は従来のHatohol stable release同様，署名付きのtagを用いる予定です。

**Comment by masa0612** [comment]
特にコメントもないようであれば，現時点でFixとし，
バージョン名は2.0.0から始めようと思います。
それぞれ，2桁目が大幅な変更，3桁目が誤字修正などの際に増えていくイメージです。

**Comment by kz0817** [comment]
はい、上記の案に同意です。

**Comment by masa0612** [comment]
作成しました。
以降は，変更があるたびにIssueを立て，どのようにバージョン変更するか議論すると良いと思います。

https://github.com/project-hatohol/HAPI-2.0-Specification/tree/2.0.0
