### ISSUE TITLE
putXXXプロシージャのresultの値についての質問

### ISSUE THREAD

**Issue by cosmo0920** [project-hatohol/HAPI-2.0-Specification#8]
`updateXXX` プロシージャではプロシージャの成功か失敗かを表す文字列がレスポンスに含まれる規定があります。
`putXXX` プロシージャにはその規定がなく、失敗してもresultには空文字が入る可能性があります。
`putXXX` プロシージャについては失敗時はresultに "FAILURE" などを入れ、HAPに送信すべき？するべきではない？

**Comment by cosmo0920** [comment]
というのも、失敗か成功かが何かしらのエラーコードで分かった方が便利だと感じたからです。

**Comment by masa0612** [comment]
putXXXをHatoholサーバーが受け取り，どの処理をもってして，
成否を表すのかわからなかったため，現在のような仕様になっています。

updateXXXは名前の通りDBをアップデートし，アップデートが成功した場合に
HAPに対してアップデート完了の旨を返します。
ItemとHistoryはデータベースに保存しない（保存したとしても重要性が薄い）ため，
上記の通り，どの処理を持ってして成否を表すかをまず定義しなければなりません。

何か案はありますか？

**Comment by cosmo0920** [comment]
うーん、そうですね…。特に良い案は思いついていないです。
putXXXもプロシージャなのでステータスを返すようにした方が良いとは思います。
が、まだ手探りなところも有るので一旦成功でも失敗でも空文字("")としてペンディングにしておきましょうか。

HAPとの通信を試す段階になってデバッグなどに有用そうだったら、
成功の時は空文字または"SUCCESS"、失敗の時は"FAILURE"をresultに入れて返す事にしましょう。

**Comment by ashie** [comment]
putXXXとupdateXXXの一貫性が無い感じがしました。

> updateXXXは名前の通りDBをアップデートし，アップデートが成功した場合に
> HAPに対してアップデート完了の旨を返します。
> ItemとHistoryはデータベースに保存しない（保存したとしても重要性が薄い）ため，

ItemはDBに保存するんですよ実は(少なくとも現在の実装では)。

じゃあfetchIdがあるのがputXXXで無いのがupdateXXX? かと言うと、updateEventsにも
fetchIdがあるようです。

全部updateXXXにしてresultも返すようにして、fetch系procedureがある奴は全部fetchIdつけるのが
一貫性があるような気がします。

**Comment by masa0612** [comment]
> > 保存したとしても重要性が薄い
> 
> ItemはDBに保存するんですよ実は(少なくとも現在の実装では)。

これはアイテムのことを指して言いました。実は最初期はアイテムもDBに保存されるためupdateだったのですが，
@kz0817 さんと相談して現在の仕様になりました。
私自身も違和感を感じている部分ではあるので，この場でもう一度話し合ったほうが良いですね。

私の意見としてはアイテムはupdateに再度修正，hisutoryに関しては，
本来の理由の通り，DBに保存しないためputを使いたいと考えています。
ただ，現在putはリザルトが空ですが，DBに保存しないとはいえ，何かしらの基準を設けて
リザルトは返したほうが良いと私も思います。

まとめると論点は２点でしょうか
- putItemsとputHistoryの名前をupdate~~~に統一するか。
- 仮にputから updateにした場合，何を持ってして”成功”と判断するか（putItemsに関してはDB書き込みで良い）

**Comment by ashie** [comment]
2015/06/11 リアルミーティングにて:
- update系とput系methodは全て形式を統一する
  - 名前はput*に統一
  - 全てのput系メソッドでSUCCESS or FAILUREを返す

**Comment by ashie** [comment]
そのように修正した
